### PR TITLE
Allow keybinding remaps

### PR DESCRIPTION
**Pull request by rentalcustard**
Hi,

Please pull this commit, which allows the default keybindings to be remapped for other purposes.

### CODE REVIEW

**Comment by astashov** [comment]
Hi!

You mean it will allow to remap e.g. \b in some another plugin/vimrc to some other action, right? Not sure I want to do that, as for me it can be source of tricky bugs. Sorry.

**Comment by rentalcustard** [comment]
That's correct. Are the bugs such that you can't fix them by putting the noremap block into your vimrc? Most other plugins don't seem to define keymappings in their script files. I appreciate that most other plugins don't have as many commands that you'd want to map as vim-ruby-debugger, but I urge you to reconsider; not being able to map certain key combinations because you have this plugin installed will be perceived as an issue with this plugin.

**Comment by rosenfeld** [comment]
This is an issue to me as I use the excelent Command-T plugin and I'm used to map it to leader-t

But I didn't like the pull request approach either. I think you might add an option for not setting any binding, so that each user could choose their preferred ones.

**Comment by rentalcustard** [comment]
Yea. I'm thinking of closing this pull request since it actually makes more sense not to have any default bindings and instead add them in users' vimrc files. On my fork I've actually taken the extra step and removed the bindings, but perhaps additionally the plugin should suggest some bindings more prominently than in its vim help. I'm not sure how optional mappings would work, but that would be cool too.

**Comment by rosenfeld** [comment]
Hi mortice,

I've changed the key bindings in my fork (branch pathogen) so that all commands starts with leader-d, so leader-b becomes leader-db and leader-t becomes leader-dt.

**Comment by abonec** [comment]
It is possible to make more convenient way to binding keys? May be some flag in my 'vimrc' to cancel default binding and custom remap in vimrc?

At this time I manually remove bindings from this plugin but it's not convenient with git =(
This plugin conflict with three of other my plugins that I use more often than debugger.

**Comment by astashov** [comment]
Just curious - what plugins vim-ruby-debugger conflicts with?
I'll try to find some good way to implement that. :)

**Comment by abonec** [comment]
Command-T (with T and B), NERD-Tree (with D), my custom bindings that I used along-time.
It's impossible to satisfy to all requirements if your plugin will always bind keys. Needed conditional bindings.

**Comment by astashov** [comment]
Okay, makes sense. I'll add possibility to specify something like

``` viml
let g:ruby_debugger_dont_add_default_mappings = 1
```

and it will not apply the default mappings in this case. Sounds good?

**Comment by abonec** [comment]
Yes. It was exactly what I want. You are great man.

**Comment by astashov** [comment]
Added `g:ruby_debugger_no_maps`.

**Comment by abonec** [comment]
Thx a lot

**Comment by noscripter** [comment]
Found `<leader>t` map conflicts with taglist.vim's default mapping. I thinks this issue is necessary.

**Pull request closed without merging**
